### PR TITLE
Add DDEV & CaptainHookPHP blog post

### PR DESCRIPTION
**Pull request by shochdoerfer**

### CODE REVIEW

**Comment by rfay** [comment]
Awesome, thanks!

A couple of notes:

* `vendor/bin` is already in the $PATH in the container
* Add a bit more to your captainhook custom command to have the expected [annotations](https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/#annotations-supported) - see other commands in ~/.ddev/commands/web
* You mention about installing git hooks either in container or on the host. Note that in the container they're in the homedir, which is not persistent. You may want to copy them into homeadditions instead.

**Comment by rfay** [comment]
Oh, forgot to say... you might really like OrbStack too. Not open source (or free) though.

**Comment by shochdoerfer** [comment]
@rfay thx for the info. Will check and adapt the blog post.

**Comment by rfay** [comment]
You might also consider making a DDEV add-on for this, making it super easy for people to use. Nothing to it...  https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#creating-an-additional-service-for-ddev-get

**Pull request merged**
