### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ekl1773**
Adding English blog translation from Thomas Kieslich TYPO3 blog

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
I think it would be respectful to Thomas to provide the links to both German and English versions, thanks! Something like
```
Customize DDEV for TYPO3 [German](link) [English](link) 
```

**Comment by rfay** [comment]
You can just push another commit, no need to start over...

**Comment by ekl1773** [comment]
Excellent point @rfay , see if that does the trick?

**Review by rfay — APPROVED** [review]
Yay!

**Pull request merged**
